version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: <RENAME_ME>-postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: <RENAME_ME>
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
